####################################
##given the fis codes from the elo.tsv file generated by elo_run.py, obtain corresponding countries of origin
## very hacky regex search of webpages, no html parsing
##some skiers cannot be found because their id changed- you'll have to replace the NAs with your own research :)
####################################

import requests
import re
import sys

SEARCH_URL = "http://data.fis-ski.com/global-links/search-a-athlete.html?listid=&lastname=&gender=ALL&sector=CC&firstname=&nation=&status=ALL&fiscode=%s&birthyear=&Search=Search&limit=1"

athlete_regex =re.compile("http://data\.fis-ski\.com/dynamic/athlete-biography\.html\?sector=CC&amp;listid=&amp;competitorid=[0-9]*")
country_regex = re.compile('<div class="column large-8 bold"><div class="sprite-flag flag-.*"></div><span class="labelpays">.*</span></div>')


## first get the codes for the skiers we need to find
file = open("./elo.tsv",'r')
lines = file.readlines()
file.close()

codes = []

for line in lines[1:]:
	fields = line.split('\t')
	codes.append(fields[0])
	
##get country codes
	
countries = []
for code in codes:
	req = requests.get(SEARCH_URL%(code))
	if req.status_code == 200:
		match = athlete_regex.search(req.text)
		if match:
			athlete_url = match.group(0).replace("&amp;","&")
			
			req2 = requests.get(athlete_url)
			if req2.status_code == 200:
				match2 = country_regex.search(req2.text)
				if match2:
					country = match2.group(0)[-16:-13] ##livin on a prayer that all countries have 3 letter codes
					countries.append(country)
				else:
					countries.append("NA")
					sys.stderr.write("Warn: during athlete search couldn't find country at url: '%s'\n"%(athlete_url))
				
				
			else:
				sys.stderr.write("Error: couldn't submit athlete search requests for code: %s\n"%(code))
				sys.exit(0)
				
			
		else:
			countries.append("NA")
			sys.stderr.write("Warn: couldn't find country for code: %s\n"%(code))
	else:
		sys.stderr.write("Error: couldn't submit search requests for code: %s\n"%(code))
		sys.exit(0)

##write to file
file = open("./countries.txt",'w')
file.write('\n'.join(countries))
file.close()